post_install() {
    systemctl enable --now sshd
    systemctl restart sshd
    ufw_setup
}

post_upgrade() {
    echo "Running upgrade now"
    systemctl stop ufw
    ufw_setup
}

post_remove() {
    ufw disable
    systemctl disable --now ufw
}

ufw_setup() {
    systemctl enable --now ufw
    ufw --force enable
    
    ufw default deny
    ufw allow from 192.168.1.0/24
    ufw allow from 63.205.195.240/28
    ufw limit ssh
    ufw logging off
}