services: 
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    user: '0'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${DOCKER_ROOT}/prometheus:/prometheus
    ports:
      - "9090:9090"
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
  
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    restart: always
    user: '0'
    environment:
     - GF_SERVER_ROOT_URL=$GRAFANA_URL
     - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - ${DOCKER_ROOT}/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
        
  jaegar:
    image: jaegertracing/all-in-one
    container_name: jaegar
    restart: always
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 16687:16687
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_ZIPKIN_COMPACT_PORT=9411
      - COLLECTOR_ZIPKIN_COMPACT