services: 
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - /data/telemetry/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /data/telemetry/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
        
  jaegar:
    image: jaegertracing/all-in-one
    container_name: jaegar
    restart: always
    ports:
      - 16686:16686
      - 16687:16687
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_ZIPKIN_COMPACT_PORT=9411
      - COLLECTOR_ZIPKIN_COMPACT
  
  otel-collector:
    image: otel/opentelemetry-collector
    container_name: otel-collector
    restart: always
    ports:
      - 4317:4317
      - 55678:55678
    volumes:
      - /data/telemetry/otel-collector:/etc/otel-collector
    command:
      - '--config=/etc/otel-collector/otel-collector-config.yaml'