services:
  wordpress:
    image: wordpress:php8.1
    container_name: musicbymalsi-wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - $DOCKER_ROOT/wordpress:/var/www/html
    ports:
      - 8080:80
    networks:
      - app-network
  db:
    image: mysql:8
    container_name: musicbymalsi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: $WORDPRESS_DB_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - $DOCKER_ROOT/mysql:/var/lib/mysql
    networks:
      - app-network
        
networks:
  app-network:
    driver: bridge