services:
  wordpress:
    image: musicbymalsi-wordpress
    container_name: musicbymalsi-wordpress-high-upload
    restart: unless-stopped
    build:
      context: ./wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - $DOCKER_ROOT/wordpress:/var/www/html
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 8080:80
    networks:
      - app-network
      - website
  db:
    image: mysql:8
    container_name: musicbymalsi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: $WORDPRESS_DB_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - $DOCKER_ROOT/mysql:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
  website:
    name: reverse-proxy
    external: true