scrape_configs:

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
    scrape_interval: 5s
      
  - job_name: 'huxley'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s