version: "3.7"

services:
  parking-page:
    container_name: parking-page
    image: rarservices.azurecr.io/parking-page:latest
    ports:
      - "5000:80"
    restart: unless-stopped
    networks:
      - personal
      - infrastructure

networks:
  personal:
    name: personal
    external: true
  infrastructure:
    name: infrastructure
    external: true