version: "3.7"

services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    ports: 
      - "6379:6379"
    volumes: 
      - ${REDIS_STORAGE}:/data
    command: redis-server --save 60 1 --loglevel warning

  nats:
    container_name: nats
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
  