services:

  registry:
    container_name: personal-registry
    image: registry:latest
    volumes:
      - ${DOCKER_ROOT}/docker-registry:/var/lib/registry
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - local

  reverse-proxy:
    image: registry.ricardoalcaraz.dev/reverse-proxy:latest
    container_name: reverse-proxy-home
    restart: unless-stopped
    volumes:
      - $DOCKER_ROOT/ricardoalcaraz.dev:/data
      - $DOCKER_ROOT/ricardoalcaraz.dev:/etc/reverse-proxy/settings.json
    environment:
      - DOTNET_ENVIRONMENT=Production
      - DOTNET_URLS=https://*:8081;http://*:8080
      #- ASPNETCORE_URLS="http://*:12121;https://*:12122;"
      #ports:
      #  - 443:443
      #  - 80:80
    networks:
      - website
      - local

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    #ports:
    #  - "8020:80"
    environment:
      DOMAIN: "https://vaultwarden.ricardoalcaraz.dev" # Your domain; vaultwarden needs to know it's https to work properly with attachments
    volumes:
      - $DOCKER_ROOT/vaultwarden:/data
    networks:
      - local

  node-exporter:
    privileged: true
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    #ports:
    #  - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1)($$|/)"
    networks:
      - local

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - /root/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

networks:
  website:
    name: reverse-proxy
    external: true
  local:
